(()=>{var D=t=>{let e=t.match(/^(\d{4})-(\d{2})-(\d{2})$/);return e?new Date(+e[1],+e[2]-1,+e[3]):null},z=t=>{let e=(t||"").split(/\n/),a=!1,o=null,i=[];for(let p of e){let n=p.trim();if(!n||n.startsWith("//"))continue;if(n==="LINEUP"){a=!0;continue}let s=n.match(/^section\s+(.+)$/i);if(s){o=s[1].trim();continue}let l=n.match(/^(\d{4}-\d{2}-\d{2})\.\.(\d{4}-\d{2}-\d{2})\s*(.*)$/);if(l){let d=D(l[1]),f=D(l[2]);if(d&&f){let{label:x,group:k}=H(l[3],o);i.push({label:x,start:d,end:f,group:k})}continue}let r=n.match(/^(\d{4}-\d{2}-\d{2})\s*(.*)$/);if(r){let d=D(r[1]);if(d){let{label:f,group:x}=H(r[2],o);i.push({label:f,start:d,end:d,group:x})}}}return{lineup:a,events:i}},H=(t,e)=>{let a=(t||"").trim().split(/\s+/),o=a.findIndex(n=>n.startsWith("#")),i=e,p=t.trim();return o>=0&&(i=a[o].slice(1),p=a.filter((n,s)=>s!==o).join(" ").trim()),{label:p,group:i}},O=(t,e,a)=>{if(e.frozen)return[...e.frozen,...a];let{lineup:o}=z(e.text);if(!o)return a;let i=$(".item").index(t),p=$(".item:lt("+i+")").filter(".calendar-source"),n=[];return p.each(function(){let s=this;if(typeof s.calendarData=="function")try{for(let l of s.calendarData())n.push({label:l.label||"",start:l.start instanceof Date?l.start:new Date(l.start),end:l.end instanceof Date?l.end:new Date(l.end||l.start),group:l.group||null})}catch{}}),[...n,...a]},W=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],A=t=>String(t).padStart(2,"0"),Y=t=>`${A(t.getDate())} ${W[t.getMonth()]} ${t.getFullYear()}`,M=(t,e={})=>{let a=e.width||400,o={top:28,right:12,bottom:16,left:8},i=22,p=14;if(!t.length)return`<svg xmlns="http://www.w3.org/2000/svg" width="${a}" height="48" viewBox="0 0 ${a} 48"><text x="${a/2}" y="28" text-anchor="middle" font-size="12" fill="#999">no events</text></svg>`;let n=1/0,s=-1/0;for(let c of t)n=Math.min(n,c.start.getTime()),s=Math.max(s,c.end.getTime());let l=s-n||864e5;n-=l*.03,s+=l*.03;let r=a-o.left-o.right,d=c=>o.left+(c-n)/(s-n)*r,f=new Map;for(let c of t){let u=c.group||"";f.has(u)||f.set(u,[]),f.get(u).push(c)}let x=[...f.entries()],k=o.top+x.length*i+p+o.bottom,g=[];g.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${a}" height="${k}" viewBox="0 0 ${a} ${k}">`),g.push(`<style>
    .tl-axis { stroke: #ccc; stroke-width: 1; }
    .tl-tick { stroke: #ccc; stroke-width: 1; }
    .tl-tick-label { font: 10px sans-serif; fill: #999; }
    .tl-lane-label { font: 10px sans-serif; fill: #888; }
    .tl-bar { rx: 3; ry: 3; cursor: pointer; }
    .tl-bar:hover rect { opacity: .8; }
    .tl-bar text { font: 11px sans-serif; fill: #fff; pointer-events: none; }
    .tl-point { cursor: pointer; }
    .tl-point:hover circle { r: 5.5; }
    .tl-point text { font: 11px sans-serif; fill: #334; pointer-events: none; }
  </style>`);let b=o.top+x.length*i;g.push(`<line class="tl-axis" x1="${o.left}" y1="${b}" x2="${a-o.right}" y2="${b}"/>`);let E=new Date(n).getFullYear(),K=new Date(s).getFullYear();for(let c=E;c<=K+1;c++){let u=new Date(c,0,1).getTime();if(u<n||u>s)continue;let w=d(u);g.push(`<line class="tl-tick" x1="${w}" y1="${b}" x2="${w}" y2="${b+5}"/>`),g.push(`<text class="tl-tick-label" x="${w}" y="${b+p}">${c}</text>`)}let S=["#5b8dd9","#d96b5b","#5bc47a","#c4a45b","#9b5bd9","#5bd9c4"];return x.forEach(([c,u],w)=>{let v=o.top+w*i+i/2,T=S[w%S.length],I=i-6;c&&g.push(`<text class="tl-lane-label" x="${o.left}" y="${v+4}">${m(c)}</text>`);for(let h of u){let y=d(h.start.getTime()),L=d(h.end.getTime());if(L-y<3)g.push(`<g class="tl-point timeline-event" data-label="${_(h.label)}"><circle cx="${y}" cy="${v}" r="4" fill="${T}" stroke="#fff" stroke-width="1.5"/><text x="${y+7}" y="${v+4}">${m(h.label)}</text></g>`);else{let F=Math.max(L-y,4);g.push(`<g class="tl-bar timeline-event" data-label="${_(h.label)}"><rect x="${y}" y="${v-I/2}" width="${F}" height="${I}" fill="${T}" opacity=".85" rx="3" ry="3"/>`+(F>40?`<text x="${y+4}" y="${v+4}" clip-path="inset(0 0 0 0)">${m(h.label)}</text>`:"")+`<title>${m(h.label)}: ${Y(h.start)}\u2013${Y(h.end)}</title></g>`)}}}),g.push("</svg>"),g.join(`
`)},m=t=>(t||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"),_=t=>(t||"").replace(/&/g,"&amp;").replace(/"/g,"&quot;"),P=(t,e)=>{let{events:a}=z(e.text),o=e.frozen?[...(e.frozen||[]).map(C),...a]:a,i=M(o);t.html('<div class="wiki-plugin-timeline" style="overflow:hidden;">'+i+'<div class="tl-controls" style="text-align:right;font-size:11px;color:#aaa;margin-top:2px;"><span class="tl-freeze" title="Freeze lineup events" style="cursor:pointer;margin-right:6px;">\u2744</span><span class="tl-expand" title="Fullscreen" style="cursor:pointer;">\u2922</span></div></div>')},C=t=>({label:t.label||"",start:new Date(t.start),end:new Date(t.end||t.start),group:t.group||null}),N=(t,e)=>{let{events:a}=z(e.text),o=O(t,e,a),i=M(o);t.find(".wiki-plugin-timeline").html(i+`<div class="tl-controls" style="text-align:right;font-size:11px;color:#aaa;margin-top:2px;"><span class="tl-freeze" title="${e.frozen?"Thaw (shift-click to restore live)":"Freeze lineup events"}" style="cursor:pointer;margin-right:6px;${e.frozen?"color:#5b8dd9":""}">\u2744</span><span class="tl-expand" title="Fullscreen" style="cursor:pointer;">\u2922</span></div>`),t.find("svg").on("click",".timeline-event",function(n){let s=this.dataset.label;if(s)try{wiki.pageHandler.context=wiki.lineup.atKey(t.closest(".page").data("key")).getContext(),wiki.doInternalLink(s,n.shiftKey?null:t.closest(".page"))}catch{}}),t.find(".tl-freeze").on("click",function(n){if(n.shiftKey&&e.frozen)delete e.frozen,delete e.svg;else{if(e.frozen)return;{let{events:s}=z(e.text),l=O(t,e,s);e.frozen=l.filter(r=>!s.includes(r)).map(r=>({label:r.label,start:r.start.toISOString(),end:r.end.toISOString(),group:r.group}))}}try{let s=t.closest(".page");wiki.pageHandler.put(s,{type:"edit",id:e.id,item:e}),wiki.doPlugin(t.empty(),e)}catch{}}),t.find(".tl-expand").on("click",()=>{let s=t.closest(".page").data("key"),l;try{l=wiki.lineup.atKey(s).getContext()}catch{l=[]}let r=window.open("/plugins/timeline/dialog/","wiki-timeline-dialog-"+s,"popup,width=900,height=600");if(!r)return;let d=M(o,{width:860}),f=()=>r.postMessage({svg:d,pageKey:s,context:l},"*");r.addEventListener("load",f,{once:!0}),setTimeout(f,800)});let p=n=>{if(n.data?.action==="doInternalLink")try{wiki.pageHandler.context=n.data.context||[],wiki.doInternalLink(n.data.title,n.data.keepLineup?t.closest(".page"):null)}catch{}};window.addEventListener("message",p),t.one("remove",()=>window.removeEventListener("message",p))};typeof window<"u"&&window!==null&&(window.plugins=window.plugins||{},window.plugins.timeline={emit:P,bind:N});})();
//# sourceMappingURL=timeline.js.map
